name: tema7
description: Movie app with redux

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.10.0
  freezed_annotation: ^2.2.0
  http: ^0.13.3
  json_annotation: ^4.7.0
  redux: ^5.0.0
  redux_epics: ^0.15.1

  rxdart: ^0.27.7



dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


  freezed: ^2.3.0
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:

  uses-material-design: true
